FROM eclipse-temurin:21

LABEL maintainer="javaguides.net@gmail.com"

WORKDIR /app

COPY build/libs/VaLocaProject-0.0.1-SNAPSHOT.jar /app/VaLocaProject.jar

ENTRYPOINT ["java","-jar","VaLocaProject.jar"]