import { useState } from 'react';
import {type JobPost} from "../../types/JobPost";
import { useNavigate, useParams } from 'react-router-dom';
import { insertPost } from '../../api/jobPostApi';
import { Context } from '../Context';
import { type JobApplication } from '../../types/JobApplication';


export default function CreateJobDataComponent() {

    const { dataType} = useParams();
    const {loggedId} = Context();

    // We use Partial so that we don't need to send all the data (postId and createdAt are generated by the backend)
    const [jobData, setjobData] = useState<Partial<JobPost | JobApplication>>({});    
    const navigate = useNavigate();


    // Logic that handles actual insertion of payload in the db
    const handleInsertion = async () => {
        try {
            if (!jobData) return null;
            await insertPost(jobData as JobPost);
            navigate("/displayJobPosts");
        } catch (error) {
            console.error("Error inserting job post:", error);
        }
    }

    // Logic that handles the string changes in the input fields and synchonizes the payload
    // NOTE: this is needed beacuse our useState object is composed, not simpl like we did in the authComponent
    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const { name, value, type } = e.target;

        setjobData((prev) => ({
            // Spread the existing state so we don't lose other fields
            ...prev, 
            // check if the type of some inputs need to be change from string to number for db acquisition
            [name]: type === "number" ? Number(value) : value 
        }));
    };

    return (
        <>
        <input value={jobData.name} name="name"  onChange={handleChange}/>
        <input value={jobData.description} name="description" onChange={handleChange}/>
        <input value={jobData.duration} name="duration" onChange={handleChange}/>
        <input value={jobData.available}  name="available" onChange={handleChange}/>
        <input value={jobData.salary} name="salary" type="number" onChange={handleChange}/>

        <button onClick={handleInsertion}>Submit</button>
        </>
    )
}